title: GitHub for Open-Source Technical Specification Development
description: A starter template for a Jekyll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://minion-of-gozer.github.io/github-for-spec-dev-course

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
